name: dropdown_search
description: Simple, reactive and highly customizable Flutter Dropdown with a lot of features (search, popups platform, async/sync,...) with multi mode like menu, dialog, bottomSheet and etc.
version: 7.0.0
homepage: https://github.com/salim-lachdhaf
git: https://github.com/salim-lachdhaf/dropdown_search
repository: https://github.com/salim-lachdhaf/dropdown_search

environment:
  sdk: ">=3.5.0 <4.0.0"


dependencies:
  cupertino_icons: ^1.0.9
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^6.1.0
  pana: ^0.23.12

topics:
  - dropdown
  - autocomplete
  - form
  - material
  - popups
